### ISSUE TITLE
求完整代码

### ISSUE THREAD

**Issue by qianwei-HFUT** [ssunguotu/ST_map#1]
您好，请问有完整的代码吗，跪求

**Comment by ssunguotu** [comment]
请问你需要的哪部分的代码，用在何处？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月28日(周一) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ssunguotu/ST_map] 求完整代码 (#1)




 
您好，请问有完整的代码吗，跪求
 
&mdash;

**Comment by qianwei-HFUT** [comment]
大佬您好，实在太感谢您回复了，我是今年刚考上研究生，提前被老师叫到实验室，才接触一点点深度学习，什么pytorch,OpenCv啥的都没有学过，然后老师就让我复现一篇论文里面的代码，论文就是RhythmNet: End-to-end Heart Rate Estimation from Face via Spatial-temporal Representation，GitHub上搜到了一个代码，也就是您这个仓库里tools文件夹里的RhythmNet，这个代码看着好乱，看不懂，然后发现了您的代码，写的实在太清晰了，十分友好，想按照您的代码将论文代码自己实现一遍，所以想问您一下有没有Face video到Spatial-temporal map的代码，就是下面这张图的代码，嗯......不知道您有没有下下面这张图的代码，这个也想要
老师还让我一两周内搞定，跪求大佬的代码




















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssunguotu/ST_map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssunguotu/ST_map] 求完整代码 (#1)





 请问你需要的哪部分的代码，用在何处？ 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年6月28日(周一) 下午4:17 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [ssunguotu/ST_map] 求完整代码 (#1) 
 
 
 
 
   
 您好，请问有完整的代码吗，跪求 
   
 &amp;mdash;

**Comment by ssunguotu** [comment]
你是考上了合工大的研究生嘛，有点巧啊，我是合工大大三的。我们加个qq聊？我的qq：876821825。
我复现的时候的代码也挺乱的...相当乱，我有时间了找找看发给你吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssunguotu/ST_map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssunguotu/ST_map] 求完整代码 (#1)





 大佬您好，实在太感谢您回复了，我是今年刚考上研究生，提前被老师叫到实验室，才接触一点点深度学习，什么pytorch,OpenCv啥的都没有学过，然后老师就让我复现一篇论文里面的代码，论文就是RhythmNet: End-to-end Heart Rate Estimation from Face via Spatial-temporal Representation，GitHub上搜到了一个代码，也就是您这个仓库里tools文件夹里的RhythmNet，这个代码看着好乱，看不懂，然后发现了您的代码，写的实在太清晰了，十分友好，想按照您的代码将论文代码自己实现一遍，所以想问您一下有没有Face video到Spatial-temporal map的代码，就是下面这张图的代码，嗯......不知道您有没有下下面这张图的代码，这个也想要 
 老师还让我一两周内搞定，跪求大佬的代码 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssunguotu/ST_map"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月28日(星期一) 晚上6:07 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ssunguotu/ST_map] 求完整代码 (#1) 
 
 
 
 
 
  请问你需要的哪部分的代码，用在何处？  
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2021年6月28日(周一) 下午4:17  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: [ssunguotu/ST_map] 求完整代码 (#1)  
   
   
   
   
     
  您好，请问有完整的代码吗，跪求  
     
  &amp;amp;mdash;
